# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wangwilly.github.io/willywangkaa
root: /willywangkaa/
permalink: :year/:month/:day/:title/
permalink_defaults:
reading_progress:
  enable: true
  color: "#37c6c0"
  height: 2px
